### ISSUE TITLE
Android build is failing

### ISSUE THREAD

**Issue by fr500** [libretro/fbalpha#109]
Not sure how recent:
http://hastebin.com/ikiberurur

**Comment by barbudreadmon** [comment]
Should be fixed, i need to rework the makefiles... Maintaining the 2 of them separately will lead to more oversights like this one.

**Comment by fr500** [comment]
Yeah I know what you mean...
Still failing http://hastebin.com/lonayolege

**Comment by barbudreadmon** [comment]
Ok, i tried to change cxxflags settings, did it work ?

**Comment by barbudreadmon** [comment]
No news, i'll consider this is solved.
