### ISSUE TITLE
fba v0.2.97.42 (7b20e50) .7z fail load roms

### ISSUE THREAD

**Issue by felixthecat1970** [libretro/fbalpha#147]
Good morning, testing fba v0.2.97.42 (7b20e50) fail load .7z roomset in 
retroarch 1.6.4 main / android 5.1 nvidia shield portable.
tested , .zip roms are ok,
tested mame core (lastest) load .7z ok
i cant test old version fba because my shield is not rooted :(

**Comment by barbudreadmon** [comment]
Makes sense since no one ported the changes we did for 7z support in makefile.libretro to jni/Android.mk

I'll port those changes, but i won't do the testing, you'll have to ask help from someone else (perhaps @webgeek1234 ?) if something goes wrong when building the android core.

**Comment by barbudreadmon** [comment]
Done, let me know if it works.

**Comment by retro-wertz** [comment]
this still does not seem to work. upon choosing a 7z file, and selecting fbalpha core, it will just show "No Items."

the same 7z file loads in linux and windows though.
tested on android 5.1, latest ra and fba core.

**Comment by barbudreadmon** [comment]
Is your core showing "f9e278f" as git version ?

**Comment by retro-wertz** [comment]
oh, my bad. its just 621e371

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by retro-wertz** [comment]
my bad.. core is still at 621e371

**Comment by barbudreadmon** [comment]
The core for android is probably not building successfully. If someone can get me some build log i'll take a look (i didn't find any for this core on the buildbot).

**Comment by retro-wertz** [comment]
i dont have idea how to cross-build. will have to wait then when buildbot
updates.

**Comment by felixthecat1970** [comment]
hello everyone, i tested new version (f5a78cc ) on 3 devices: 
android nougat 7.1.2 / RA 1.6.7:  .7z romset  (fixed)
raspberry (retropie 4.2+ last update) :  .7z romset fbaalpha (roms with 40+mb size fail to load)
                                                            update core from source to (f5a78cc) (fix the problem)
psvita 3.60 / RA 1.6.7: .7z roomset (f5a78cc) ( fail to load roms, .zip ok)
Now seems fixed for android and raspberry; but psvita has problem maybe 3ds too (i will check next days)
Thanks for help.

**Comment by fr500** [comment]
@barbudreadmon 

```
<retrobot> fbalpha-armeabi: [status: done] [recipes/android/cores-android-jni]
<retrobot> fbalpha-armeabi-v7a: [status: done] [recipes/android/cores-android-jni]
<retrobot> fbalpha-x86: [status: done] [recipes/android/cores-android-jni]
<retrobot> fbalpha-arm64-v8a: [status: done] [recipes/android/cores-android-jni-aarch64]
```

No errors. We only record the logs for failures

**Comment by barbudreadmon** [comment]
I don't see any reason why it would fail on psvita
