### ISSUE TITLE
Can't steer in outrun.

### ISSUE THREAD

**Issue by blackman91** [libretro/fbalpha#150]
I am using Retroarch latest nightly on Android 7 with a gamepad but I can't move the car at all in outrun, not with the dpad or the analog stick, tested also with the touchscreen overlay and it doesn't work too, all the other buttons work.

**Comment by barbudreadmon** [comment]
Duplicate with #102 : it seems there is indeed an issue on android with analog controls, i'm not really sure it is a core issue though, does android's retroarch support analog controls ? Some confirmation from retroarch's developpers ( @twinaphex ? ) would be nice.

**Comment by barbudreadmon** [comment]
It should be solved. Android and other systems didn't use the same gamc.cpp/gami.cpp, i took care of that.

**Comment by blackman91** [comment]
Nice! It works now but the bug is still present in the fba 2012 core, should I open an issue there?

**Comment by barbudreadmon** [comment]
Well, they probably have the same issue. Yes you should tell them.
